### PR TITLE
Add zod.json in italian (IT)

### PR DESCRIPTION
**Pull request by Balastrong**
Cool library, I wanted to use it on a project but italian was missing so there it is :)

### CODE REVIEW

**Comment by aiji42** [comment]
@Balastrong Grazi!!
You need to add a test file.
Also, adding the Italian translation file to the example will help others find examples of using this library.
Please refer to the pull requests of other contributors. https://github.com/aiji42/zod-i18n/pull/48

**Comment by Balastrong** [comment]
Hey @aiji42! Sorry I just translated it in local for my project and pasted it here, not really the right way 😅

I'll properly read the docs and update the PR accordingly tomorrow, thank you for the guidance!

**Comment by aiji42** [comment]
Great! Will merge and release as soon as testing passes.

**Comment by aiji42** [comment]
@all-contributors please add @Balastrong for translation and test

**Pull request merged**
